### ISSUE TITLE
自定义HEXO站内搜索Javascript+json | 秋过冬漫长

### ISSUE THREAD

**Issue by chaooo** [chaooo/BlogComments#4]
https://chaooo.github.io/2016/11/09/json-search.html
https://chaoo.gitee.io/2016/11/09/json-search.html
 郑超的个人博客，Charles·Zheng's blog.

**Comment by chenkuna** [comment]
您是怎么把这个评论的放在下面的鸭 是在每个md文件下面加下面这个代码吗   可是他会在分享的上面有点难看

<script src="https://utteranc.es/client.js"
        repo="nusr/blog"
        issue-term="pathname"
        theme="github-light"  
        crossorigin="anonymous"
        async>
</script>

**Comment by chaooo** [comment]
> @chenkuna
> 您是怎么把这个评论的放在下面的鸭 是在每个md文件下面加下面这个代码吗   可是他会在分享的上面有点难看
> 
> <script src="https://utteranc.es/client.js"
>         repo="nusr/blog"
>         issue-term="pathname"
>         theme="github-light"  
>         crossorigin="anonymous"
>         async>
> </script>

在主题配置文件_congig.yml中开启就好
``` 
#Cmments
comment:
  gitalk:
    enable: false ## If you want to use Gitment comment system please set the value to true.
    owner: ## Your GitHub ID, e.g. username
    repo: ## The repository to store your comments, make sure you're the repo's owner, e.g. gitalk.github.io
    client_id: ## GitHub client ID, e.g. 75752dafe7907a897619
    client_secret: ## GitHub client secret, e.g. ec2fb9054972c891289640354993b662f4cccc50
    admin: ## Github repo owner and collaborators, only these guys can initialize github issues.
    language: zh-CN ## Language
    pagerDirection: last # Comment sorting direction, available values are last and first.
```
